// tools/build-css.modern.mjs — 把 modern 面板的 Tailwind v4 输入编译成静态 CSS 字符串，
// 生成 src/ui/stylesModern.generated.mjs（已提交，故 build:bookmarklet 无需 Tailwind 工具链，
// 与 build-css.mjs / styles.generated.mjs 同策略）。
//
//   bun run build:css:modern   → 改了 modern 面板/图标类名或 tailwind.modern.css 后重新生成
//
// 用 @tailwindcss/cli(v4)。扫描的源文件由 tailwind.modern.css 里的 @source 指定
// （panelModern.mjs / iconsMicro.mjs / blockTree.mjs）。classic 走 build-css.mjs（v3），互不干扰。

import { spawnSync } from "node:child_process";
import { readFileSync, writeFileSync, mkdtempSync, rmSync } from "node:fs";
import { resolve, dirname, join } from "node:path";
import { fileURLToPath } from "node:url";
import { tmpdir } from "node:os";

const ROOT = resolve(dirname(fileURLToPath(import.meta.url)), "..");
const input = resolve(ROOT, "src/ui/tailwind.modern.css");
const out = resolve(ROOT, "src/ui/stylesModern.generated.mjs");

const tmp = mkdtempSync(join(tmpdir(), "m3e-css-modern-"));
const cssFile = join(tmp, "out.css");

// 显式走 @tailwindcss/cli(v4) 的入口，不依赖共享的 node_modules/.bin/tailwindcss
// （那个 bin 名被 v3 与 v4 争用，取决于安装顺序）。
const v4cli = resolve(ROOT, "node_modules/@tailwindcss/cli/dist/index.mjs");
const res = spawnSync(process.execPath, [v4cli, "-i", input, "-o", cssFile, "--minify"], {
  cwd: ROOT,
  encoding: "utf8",
  stdio: ["ignore", "pipe", "pipe"],
});
if (res.status !== 0) {
  console.error(res.stderr || res.stdout || "tailwindcss(v4) 失败");
  rmSync(tmp, { recursive: true, force: true });
  process.exit(1);
}

const css = readFileSync(cssFile, "utf8");
rmSync(tmp, { recursive: true, force: true });

const banner =
  "// src/ui/stylesModern.generated.mjs — GENERATED by tools/build-css.modern.mjs. Do not edit.\n" +
  "// Precompiled Tailwind v4 CSS (modern theme), inlined into the modern panel's Shadow DOM <style>.\n";
writeFileSync(out, `${banner}export const PANEL_CSS_MODERN = ${JSON.stringify(css)};\n`);
console.error(`[build:css:modern] ${(css.length / 1024).toFixed(1)}KB → src/ui/stylesModern.generated.mjs`);
