// tools/build-css.mjs — Compile the panel's Tailwind input into a static CSS
// string and emit src/ui/styles.generated.mjs (committed, so build:bookmarklet
// works without the Tailwind toolchain — like build:catalog vs build:bookmarklet).
//
//   bun run build:css   → regenerate after changing panel classes or tailwind.css
//
// Scans src/ui/** for utility classes (see tailwind.config.cjs).

import { spawnSync } from "node:child_process";
import { readFileSync, writeFileSync, mkdtempSync, rmSync } from "node:fs";
import { resolve, dirname, join } from "node:path";
import { fileURLToPath } from "node:url";
import { tmpdir } from "node:os";

const ROOT = resolve(dirname(fileURLToPath(import.meta.url)), "..");
const input = resolve(ROOT, "src/ui/tailwind.css");
const out = resolve(ROOT, "src/ui/styles.generated.mjs");

const tmp = mkdtempSync(join(tmpdir(), "m3e-css-"));
const cssFile = join(tmp, "out.css");

const bin = resolve(ROOT, "node_modules/.bin/tailwindcss");
const res = spawnSync(bin, ["-i", input, "-o", cssFile, "--minify"], {
  cwd: ROOT,
  encoding: "utf8",
  stdio: ["ignore", "pipe", "pipe"],
});
if (res.status !== 0) {
  console.error(res.stderr || res.stdout || "tailwindcss 失败");
  rmSync(tmp, { recursive: true, force: true });
  process.exit(1);
}

const css = readFileSync(cssFile, "utf8");
rmSync(tmp, { recursive: true, force: true });

const banner =
  "// src/ui/styles.generated.mjs — GENERATED by tools/build-css.mjs. Do not edit.\n" +
  "// Precompiled Tailwind CSS, inlined into the panel's Shadow DOM <style>.\n";
writeFileSync(out, `${banner}export const PANEL_CSS = ${JSON.stringify(css)};\n`);
console.error(`[build:css] ${(css.length / 1024).toFixed(1)}KB → src/ui/styles.generated.mjs`);
